name = "Delivery app"
# keep the rest aligned with the main config, but importantly:
# 1) remove webhook subscriptions
# 2) remove app_proxy

[access_scopes]
scopes = "write_products,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"

[webhooks]
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = false
